# Generated by Django 6.0.6 on 2026-06-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('categoria', models.CharField(choices=[('LAPTOP', 'Laptops'), ('CELULAR', 'Celulares'), ('PERIFERICO', 'Periféricos'), ('COMPONENTE', 'Componentes'), ('ACCESORIO', 'Accesorios')], default='ACCESORIO', max_length=50)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
